apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc.cluster.local:8200"
        # the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"
        vault.security.banzaicloud.io/vault-role: "default"
        # optional, skip TLS verification of the Vault server certificate
        #vault.security.banzaicloud.io/vault-skip-verify: "false"
        # optional, the name of the Secret where the Vault CA cert is, if not defined it is not mounted
        #vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        # optional, if true, a Vault Agent will be started to do Vault authentication, by default not needed and vault-env will do Kubernetes Service Account based Vault authentication
        # vault.security.banzaicloud.io/vault-agent: "false"
        # optional, the Kubernetes Auth mount path in Vault the default value is "kubernetes"
        # vault.security.banzaicloud.io/vault-path: "kubernetes"
        # Add this annotation to skip mutations
        # vault.security.banzaicloud.io/mutate: "skip"
    spec:
      serviceAccountName: default
      containers:
        - name: demo-app
          image: ghcr.io/sagikazarmark/http-echo2:v0.3.0
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              value: vault:secret/data/accounts/aws#AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-aws
                  key: secret-key
          envFrom:
            - configMapRef:
                name: demo-mysql
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 10m
