---
apiVersion: v1
kind: Secret
metadata:
  name: demo-aws
  namespace: default
  annotations:
    vault.security.banzaicloud.io/mutate: "skip"
stringData:
  secret-key: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
