# Example Promtail installation for EKS
# https://grafana.com/docs/loki/latest/send-data/promtail/cloud/eks/
---
config:
  enabled: true
  logLevel: info
  logFormat: logfmt
  serverPort: 3100
  clients:
    - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

extraScrapeConfigs:
  - job_name: journal
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'

extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal

extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true
