---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/silazare/argocd-infra-example'
    targetRevision: HEAD
    path: vault
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - chart: bank-vaults/helm-charts/vault-operator
      repoURL: ghcr.io
      targetRevision: 1.22.1
      helm:
        valueFiles:
          - bank-vaults/helm-values/vault-operator-values.yaml
    - repoURL: 'https://github.com/silazare/argocd-infra-example'
      targetRevision: HEAD
      path: bank-vaults/manifests
