---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
  # To remove pruned resources automatically
  # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # App manifest from Git
    - repoURL: 'https://github.com/silazare/argocd-infra-example'
      targetRevision: HEAD
      path: demo-app/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
